// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEticketApplication.Data;

#nullable disable

namespace MyEticketApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221231000549_fourth")]
    partial class fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyEticketApplication.Models.RouteFrom", b =>
                {
                    b.Property<int>("RouteFromId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteFromId"));

                    b.Property<string>("RouteFromName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteToId")
                        .HasColumnType("int");

                    b.HasKey("RouteFromId");

                    b.HasIndex("RouteToId");

                    b.ToTable("RouteFroms");
                });

            modelBuilder.Entity("MyEticketApplication.Models.RouteTo", b =>
                {
                    b.Property<int>("RouteToId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteToId"));

                    b.Property<string>("RouteToName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteToId");

                    b.ToTable("RouteToFroms");
                });

            modelBuilder.Entity("MyEticketApplication.Models.TransportInfo", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportId"));

                    b.Property<int>("SeatNo")
                        .HasColumnType("int");

                    b.Property<string>("TransportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int");

                    b.HasKey("TransportId");

                    b.HasIndex("TransportTypeId");

                    b.ToTable("TransportInfo");
                });

            modelBuilder.Entity("MyEticketApplication.Models.TransportType", b =>
                {
                    b.Property<int>("TransportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransportTypeId");

                    b.ToTable("TransportTypes");
                });

            modelBuilder.Entity("MyEticketApplication.Models.RouteFrom", b =>
                {
                    b.HasOne("MyEticketApplication.Models.RouteTo", "RouteTo")
                        .WithMany("RouteFroms")
                        .HasForeignKey("RouteToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteTo");
                });

            modelBuilder.Entity("MyEticketApplication.Models.TransportInfo", b =>
                {
                    b.HasOne("MyEticketApplication.Models.TransportType", "TransportTypes")
                        .WithMany("TransportInfos")
                        .HasForeignKey("TransportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportTypes");
                });

            modelBuilder.Entity("MyEticketApplication.Models.RouteTo", b =>
                {
                    b.Navigation("RouteFroms");
                });

            modelBuilder.Entity("MyEticketApplication.Models.TransportType", b =>
                {
                    b.Navigation("TransportInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
